services:
  service.import:
    class: ImportBundle\Services\Import
    arguments: [ "@service_container" ]

  service.import_csv_service:
    class: ImportBundle\Services\ImportCSVService
    arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]

