<?php
/**
 * PHP version: 5.6+
 */
namespace ImportBundle\Repository;

/**
 * ProductDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @codeCoverageIgnore
 */
class ProductDataRepository extends \Doctrine\ORM\EntityRepository
{

}
