<?php

namespace ImportBundle\Repository;

/**
 * ProductDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDataRepository extends \Doctrine\ORM\EntityRepository
{
}
