<?php

namespace ImportBundle\Repository;

/**
 * TblproductdataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblproductdataRepository extends \Doctrine\ORM\EntityRepository
{
}
